Eigenproject/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayerLibrary.DataLogic;
using DataLayerLibrary.DataModels;
using Eigenproject.Models;
using LogicLayerLibrary.ExtensionMethods;
using Microsoft.AspNetCore.Mvc;

namespace Eigenproject.Controllers
{
    public class SubscriptionController : Controller
    {
        public IActionResult GetListOfSubscriptionViaUserId(int user_Id)
        {
            List<SubscriptionDataModel> data = SubscriptionProcessor.GetSubscriptionsViaUserId(user_Id);
            List<SubscriptionModel> subscriptions = new List<SubscriptionModel>();
            foreach (var subscription in data)
            {
                subscriptions.Add(new SubscriptionModel
                {
                    Name = subscription.SubscriptionName,
                    Id = subscription.Id,
                    User_Id = subscription.User_Id,
                    type = subscription.Type
                });
            }

            if (data.Count == 0)
            {
                subscriptions = null;
            }

            return View(subscriptions);
        }

        [HttpPost]
        public IActionResult AddGenreSubscription([FromBody]string subscriptionName)
        {
            SubscriptionProcessor.CreateSubscription(subscriptionName, "Genre", HttpContext.GetCurrentUserModel().User_Id);
            return null;
        }

        [HttpPost]
        public IActionResult AddUserSubscription([FromBody]string subscriptionName)
        {
            SubscriptionProcessor.CreateSubscription(subscriptionName, "User", HttpContext.GetCurrentUserModel().User_Id);
            return null;
        }

        [HttpPost]
        public IActionResult AddTagSubscription([FromBody]string subscriptionName)
        {
            SubscriptionProcessor.CreateSubscription(subscriptionName, "Tag", HttpContext.GetCurrentUserModel().User_Id);
            return null;
        }

        [HttpPost]
        public IActionResult RemoveSubscription([FromBody] string subscriptionName)
        {
            SubscriptionProcessor.RemoveSubscription(HttpContext.GetCurrentUserModel().User_Id, subscriptionName);
            return null;
        }
    }
}

Eigenproject/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DataLayerLibrary.DataLogic;
using DataLayerLibrary.DataModels;
using Eigenproject.Models;
using Microsoft.AspNetCore.Mvc;
using LogicLayerLibrary;
using LogicLayerLibrary.ExtensionMethods;
using Microsoft.AspNetCore.Authentication;
using Org.BouncyCastle.Crypto.Parameters;

namespace Eigenproject.Controllers
{
    public class UserController : Controller
    {
        public IActionResult RegisterUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterUser(UserModel user)
        {
            UserDataModel tempdata = new UserDataModel();
            try
            {
                tempdata = UserProcessor.GetUserByUserName(user.UserName);
            }
            catch
            {

            }
            if (tempdata.Email == user.Email)
            {
                ModelState.AddModelError("", "Email already in use");
                return View();
            }
            else if (tempdata.UserName == user.UserName)

            {
                ModelState.AddModelError("", "Username already in use");
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    string salt = HashingLogic.GenerateSalt();
                    string password = HashingLogic.GenerateHash(salt, user.Password);
                    UserProcessor.CreateUser(
                        user.Email,
                        user.DateOfBirth,
                        password,
                        user.UserName,
                        salt

                    );
                    return RedirectToAction("ViewPosts", "Post");
                }
                return View();
            }
        }


        public IActionResult LoginUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LoginUser(LoginUserModel login)
        {
            UserDataModel userData = UserProcessor.GetUserByUserName(login.Username);
            bool isValid = HashingLogic.CheckPassword(userData.Salt, userData.Password, login.Password);
            if (isValid)
            {
                var UserClaims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, userData.UserName),
                };

                var UserIdentity = new ClaimsIdentity(UserClaims, "User Identity");
                var UserPrincipal = new ClaimsPrincipal(new[] { UserIdentity });

                HttpContext.SignInAsync(UserPrincipal);
                return RedirectToAction("ViewPosts", "Post");
            }
            else
            {
                ModelState.AddModelError("", "Password or username incorrect");
            }
            return View();
        }

        public IActionResult UpdateUser(string username)
        {
            var model = UserProcessor.GetUserByUserName(username);
            var data = new UserModel
            {
                Email = model.Email,
                Password = model.Password,
                UserName = model.UserName,
                User_Id = model.User_Id
            };

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateUser(UserModel model)
        {
            var Salt = UserProcessor.GetUserByUserName(HttpContext.GetCurrentUserModel().UserName).Salt;
            UserProcessor.UpdateUser(model.Email, HashingLogic.GenerateHash(Salt, model.Password), model.UserName, HttpContext.GetCurrentUserModel().User_Id);
            return RedirectToAction("ViewPosts", "Post");
        }

        public IActionResult DetailsUser(string username)
        {
            var datamodel = UserProcessor.GetUserByUserName(username);
            UserModel data = new UserModel
            {
                CreationDate = datamodel.CreationDate,
                DateOfBirth = datamodel.DateOfBirth,
                Email = datamodel.Email,
                Password = datamodel.Password,
                Points = datamodel.Points,
                UserName = datamodel.UserName
            };
            return View(data);
        }

        public IActionResult DeleteUser()
        {
            var user_Id = HttpContext.GetCurrentUserModel().User_Id;
            HttpContext.SignOutAsync();
            var postdata = PostProcessor.GetPostsByUserId(user_Id);
            foreach (var post in postdata)
            {
                PostProcessor.DeletePost(post.Post_Id);
                FileProcessor.DeleteFile(post.File_Id);
            }

            var subscriptiondata = SubscriptionProcessor.GetSubscriptionsViaUserId(user_Id);
            foreach (var subscription in subscriptiondata)
            {
                SubscriptionProcessor.RemoveSubscription(user_Id, subscription.SubscriptionName);
            }
            UserProcessor.DeleteUser(user_Id);

            return RedirectToAction("ViewPosts", "Post");
        }

        public IActionResult LogOutUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                HttpContext.SignOutAsync();
            }
            return RedirectToAction("ViewPosts", "Post");
        }
    }
}

Eigenproject/ViewComponents/GenreSidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Text;
using DataLayerLibrary.DataLogic;
using Eigenproject.Models;

namespace DataLayerLibrary.ViewComponents
{
    public class GenreSidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var data = SubscriptionProcessor.GetFiveMostRecurringGenres();
            List<GenreModel> genres = new List<GenreModel>();
            foreach (var row in data)
            {
                var genreData = GenreProcessor.GetGenreByName(row.SubscriptionName);
                genres.Add(new GenreModel()
                    {
                        Id = genreData.ID,
                        Name = genreData.name
                    }
                );
            }
            return View(genres);
        }
    }
}

Eigenproject/ViewComponents/TagSidebarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayerLibrary.DataLogic;
using Eigenproject.Models;
using Microsoft.AspNetCore.Mvc;

namespace Eigenproject.ViewComponents
{
    public class TagSidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var data = SubscriptionProcessor.GetFiveMostRecurringTags();
            List<TagModel> tags = new List<TagModel>();
            foreach (var row in data)
            {
                var tagData = TagsProcessor.GetTagByName(row.SubscriptionName);
                tags.Add(new TagModel
                {
                    Id = tagData.ID,
                    Name = tagData.name
                }
                );
            }
            return View(tags);
        }
    }
}

Eigenproject/Views/Shared/_Layout.cshtml
@using LogicLayerLibrary.ExtensionMethods

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GamerHaven</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/sidebar.css" />
    <link rel="stylesheet" href="~/css/sidebarRight.css" />
    <link rel="stylesheet" href="~/css/SearchBar.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <form asp-controller="Post" asp-action="GetPostsByTitle" name="myForm" onsubmit="return validateForm()" method="get" required>
        <div class="wrap">
            <div class="search">
                <input type="text" class="searchTerm" placeholder="Find posts" name="title">
                <button type="submit" value="save" class="searchButton">
                        <i class="fa fa-search"></i>
                    </button>
            </div>
        </div>
    </form>
    <div class="searchBox">
    </div>



    <div class="container">
        <main role="main" class="pb-3">
            <div id="viewport">

                <!-- SidebarRight -->
                <div id="sidebarRight">
                    @if (Context.GetCurrentUserModel() == null)
                    {
                        <header>
                            @Html.ActionLink("Login", "LoginUser", "User")
                        </header>
                    }
                    else
                    {
                        <header>
                            @Html.ActionLink(@Context.GetCurrentUserModel().UserName, "DetailsUser", "User",  new {username = @Context.GetCurrentUserModel().UserName})
                        </header>
                    }
                <ul class="nav">
                    @await Component.InvokeAsync("GenreSidebar")
                    @await Component.InvokeAsync("TagSidebar")
                </ul>
                </div>

                <!-- Sidebar -->
                <div id="sidebar">
                    <header>
                        <a asp-controller="Post" asp-action="ViewPosts">GamerHaven <img src="~/DesignImages/Logo.png" style="width: 60px;"/></a> 
                    </header>
                    <ul class="nav">
                        <li>
                            <a asp-controller="Post" asp-action="ViewPosts">
                                <i class="zmdi zmdi-view-dashboard"></i>Home
                            </a>
                        </li>
                        @if (Context.GetCurrentUserModel() != null)
                        {
                            <li>
                                <a asp-controller="User" asp-action="DetailsUser" asp-route-username="@Context.GetCurrentUserModel().UserName">
                                    <i class="zmdi zmdi-link"></i>Account
                                </a>

                            </li>
                            <li>
                                <a asp-controller="Subscription" asp-action="GetListOfSubscriptionViaUserId" asp-route-user_Id="@Context.GetCurrentUserModel().User_Id">
                                    <i class="zmdi zmdi-calendar"></i>Subscriptions
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Post" asp-action="CreatePost">
                                    <i class="zmdi zmdi-widgets"></i>Create Post
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Post" asp-action="GetPostsByUserId" asp-route-user_Id="@Context.GetCurrentUserModel().User_Id">
                                    <i class="zmdi zmdi-widgets"></i>My Posts
                                </a>
                            </li>

                        }
                        else
                        {
                        <li>
                            <a  onclick="Onclick()" href="#">
                                <i class="zmdi zmdi-link"></i>Account
                            </a>

                        </li>
                        <li>
                            <a  onclick="Onclick()" href="#">
                                <i class="zmdi zmdi-calendar"></i>Subscriptions
                            </a>
                        </li>
                        <li>
                            <a  onclick="Onclick()" href="#">
                                <i class="zmdi zmdi-widgets"></i>Create Post
                            </a>
                        </li>
                        <li>
                            <a onclick="Onclick()" href="#">
                                <i class="zmdi zmdi-widgets"></i>My Posts
                            </a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
            @RenderBody()
        </main>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
<script>
    function validateForm() {
        var x = document.forms["myForm"]["title"].value;
        if (x == "") {
            alert("Name must be filled out");
            return false;
        }
    }
</script>
<script>
    function Onclick() {
            if (confirm("Can't do this while not logged in. Do you want to log in?")) {
                window.location.href= "@Url.Action("LoginUser", "User")";;
            }

        }
</script>
    @RenderSection("Scripts", required: false)
</body>
</html>